//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pet_adoption_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Adopter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adopter()
        {
            this.AdoptionEntries = new HashSet<AdoptionEntry>();
        }
    
        public int AdopterId { get; set; }
        [Display(Name ="Adopt Name"),Required]
        public string AdopterName { get; set; }
        [Display(Name ="Birthdate"),Required,Column(TypeName ="date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime BirthDate { get; set; }
        [Display(Name = "Age"), Required]
        public int Age { get; set; }
        public string Picture { get; set; }
        [Display(Name = "Marital Status"), Required]
        public bool Maritalstatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdoptionEntry> AdoptionEntries { get; set; }
    }
}
