//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pet_adoption_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdoptionEntry
    {
        public int AdoptionEntryID { get; set; }
        [Display(Name="Pet"),Required]
        public int PetId { get; set; }
        [Display(Name ="Adopter"),Required]
        public int AdopterId { get; set; }
        public virtual Adopter Adopter { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
